/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_weblite_webview_WebViewNative */

#ifndef _Included_ca_weblite_webview_WebViewNative
#define _Included_ca_weblite_webview_WebViewNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_create
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1create
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_run
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1run
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_terminate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1terminate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_dispatch
 * Signature: (JLjava/lang/Runnable;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1dispatch
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_get_window
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1get_1window
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_set_title
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1set_1title
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_set_bounds
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1set_1bounds
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_navigate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1navigate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_init
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_eval
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1eval
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_bind
 * Signature: (JLjava/lang/String;Lca/weblite/webview/WebViewNativeCallback;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1bind
  (JNIEnv *, jclass, jlong, jstring, jobject, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    jawt_get_window_handle
 * Signature: (Ljava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_jawt_1get_1window_1handle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_create
 * Signature: (Ljava/awt/Component;I)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1create
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_set_bounds
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1set_1bounds
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_pump
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1pump
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_navigate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1navigate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_init
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_eval
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1eval
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_bind
 * Signature: (JLjava/lang/String;Lca/weblite/webview/WebViewNativeCallback;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1bind
  (JNIEnv *, jclass, jlong, jstring, jobject, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_dispatch
 * Signature: (JLjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1dispatch
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_set_visible
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1set_1visible
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_request_focus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1request_1focus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_create
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1create
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_resize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1resize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_navigate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1navigate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_snapshot
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1snapshot
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_mouse_button
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1mouse_1button
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_mouse_motion
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1mouse_1motion
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_mouse_scroll
 * Signature: (JIIDDI)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1mouse_1scroll
  (JNIEnv *, jclass, jlong, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_key_event
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1key_1event
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_open_devtools
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1open_1devtools
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_execute_editing_command
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1execute_1editing_1command
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_is_native_first_responder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1is_1native_1first_1responder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_set_focus_callback
 * Signature: (JLca/weblite/webview/WebViewFocusCallback;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1set_1focus_1callback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_embed_release_native_focus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1embed_1release_1native_1focus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_init
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_eval
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1eval
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_bind
 * Signature: (JLjava/lang/String;Lca/weblite/webview/WebViewNativeCallback;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1bind
  (JNIEnv *, jclass, jlong, jstring, jobject, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_dispatch
 * Signature: (JLjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1dispatch
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_open_devtools
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1open_1devtools
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_offscreen_execute_editing_command
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1offscreen_1execute_1editing_1command
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
